include: package:flutter_lints/flutter.yaml
linter:
  rules:
    library_private_types_in_public_api: false
    prefer_single_quotes: true 
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
  errors:
    todo: ignore
    invalid_annotation_target: ignore
