name: work_timer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  floor: ^1.4.2
  shamsi_date: ^1.0.2
  mobx: ^2.3.3
  flutter_mobx: ^2.2.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  page_transition: ^2.1.0
  iconsax: ^0.0.8
  persian_datetime_picker: ^2.6.0
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  toastification: ^1.2.1
  gap: ^3.0.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  floor_generator: ^1.4.2
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  analyzer: ^6.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: comfortaa
      fonts:
        - asset: assets/fonts/comfortaa.ttf
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
    - family: sahel
      fonts:
        - asset: assets/fonts/sahel.ttf
        - asset: assets/fonts/sahel_bold.ttf
          weight: 700
